// Auto-generated by sv_wrap.py from aes.sv

module wrap (
  input logic clk,
  input logic rst_n,
  input logic[127:0] plaintext,
  input logic plaintext_valid,
  input logic[127:0] key,
  output logic[127:0] ciphertext,
  output logic ciphertext_valid
);

  // Registered inputs
  logic[127:0] plaintext_d1;
  logic plaintext_valid_d1;
  logic[127:0] key_d1;

  // DUT outputs, before registering
  logic[127:0] ciphertext_early;
  logic ciphertext_valid_early;

  // Device under test
  aes dut (
    .clk(clk),
    .rst_n(rst_n),
    .plaintext(plaintext_d1),
    .plaintext_valid(plaintext_valid_d1),
    .key(key_d1),
    .ciphertext(ciphertext_early),
    .ciphertext_valid(ciphertext_valid_early)
  );

  // Input and output registers
  always_ff @(posedge clk) begin
    if (!rst_n) begin
      plaintext_d1 <= '0;
      plaintext_valid_d1 <= '0;
      key_d1 <= '0;
      ciphertext <= '0;
      ciphertext_valid <= '0;
    end else begin
      plaintext_d1 <= plaintext;
      plaintext_valid_d1 <= plaintext_valid;
      key_d1 <= key;
      ciphertext <= ciphertext_early;
      ciphertext_valid <= ciphertext_valid_early;
    end
  end

endmodule
